import React,{useEffect,useRef,useState} from 'react';
export const whatsapp='https://wa.me/5551998133404?text='+encodeURIComponent('Olá! Vim pelo site da Serralheria LC e gostaria de solicitar um orçamento.');
const base='/images/';
const photos=[
 ['pergolados/pergolado-metalico-iluminado-campo-bom.webp','Pergolado metálico com iluminação','Uma nova forma de aproveitar o espaço.'],
 ['pergolados/pergolado-area-externa-campo-bom.webp','Pergolado para área externa','Metal e madeira em harmonia.'],
 ['pergolados/cobertura-metalica-residencial-campo-bom.webp','Cobertura metálica residencial','Proteção sob medida para o dia a dia.'],
 ['pergolados/cobertura-metalica-vista-frontal-campo-bom.webp','Cobertura metálica · vista frontal','Estrutura que acompanha a arquitetura.'],
 ['estruturas-metalicas/estrutura-metalica-cobertura-em-montagem-campo-bom.webp','Estrutura de cobertura em montagem','Cada etapa faz parte do resultado.'],
 ['estruturas-metalicas/estrutura-pergolado-em-montagem-campo-bom.webp','Pergolado em montagem','Do projeto à instalação.']];
function WA({children='Solicitar orçamento',className=''}){return <a className={'button '+className} href={whatsapp} target="_blank" rel="noopener noreferrer">{children}</a>}
export default function App(){const [menu,setMenu]=useState(false),[selected,setSelected]=useState(null);const dialog=useRef(null),trigger=useRef(null);useEffect(()=>{if(selected!==null){dialog.current.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[selected]);function close(){setSelected(null);trigger.current?.focus()}function open(i,e){trigger.current=e.currentTarget;setSelected(i)}
 return <><a className="skip" href="#principal">Pular para o conteúdo</a><header><div className="container header-inner"><a className="brand" href="#" aria-label="Serralheria LC início"><img src="/images/brand/logo-serralheria-lc.webp" width="64" height="64" alt="Logo LC com serralheiro"/><span>SERRALHERIA <b>LC</b><small>CAMPO BOM · RS</small></span></a><button className="menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} aria-controls="navegacao" onClick={()=>setMenu(!menu)}>{menu?'Fechar':'Menu'}</button><nav id="navegacao" className={menu?'open':''} aria-label="Navegação principal"><a href="#servicos" onClick={()=>setMenu(false)}>Serviços</a><a href="#trabalhos" onClick={()=>setMenu(false)}>Trabalhos</a><a href="#sobre" onClick={()=>setMenu(false)}>A LC</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a><WA/></nav></div></header>
 <main id="principal"><section className="hero"><div className="hero-copy"><p className="eyebrow">SERRALHERIA EM CAMPO BOM E REGIÃO</p><h1>Pergolados e estruturas metálicas <em>feitos para durar.</em></h1><p className="intro">Seu espaço merece um projeto bem feito. Fabricamos sob medida e cuidamos de cada detalhe até a instalação.</p><div className="actions"><WA>Solicitar orçamento no WhatsApp</WA><a className="text-link" href="#trabalhos">Ver nossos trabalhos</a></div><div className="hero-proof"><strong>+8 <span>anos de experiência</span></strong><span className="proof-note">Projetos reais.<br/>Trabalho de quem conhece o metal.</span></div></div><div className="hero-visual"><img src={base+photos[0][0]} alt="Pergolado metálico da Serralheria LC com iluminação em corredor residencial" width="960" height="1280" fetchPriority="high"/><div className="image-note"><span>OBRA REAL · SERRALHERIA LC</span><p>Mais uso para o seu espaço.<br/>Mais valor para a sua casa.</p></div><span className="vertical-label">SOB MEDIDA. DO INÍCIO AO FIM.</span></div></section>
 <div className="qualities"><div className="container"><span>Fabricação sob medida</span><span>Campo Bom e região</span><span>Residencial e comercial</span><span>Cuidado no acabamento</span></div></div>
 <section className="section container" id="servicos"><div className="section-heading"><div><p className="eyebrow">01 / O QUE FAZEMOS</p><h2>Metal que dá forma<br/>ao seu projeto.</h2></div><p>Estruturas pensadas para o seu espaço, com fabricação própria e atendimento próximo.</p></div><div className="services"><article><img src={base+photos[1][0]} alt="Pergolado com estrutura metálica e cobertura de madeira em área de convivência" loading="lazy" width="960" height="1280"/><div><span className="service-number">01</span><h3>Pergolados</h3><p>Uma área externa mais acolhedora e funcional. Medidas e acabamento de acordo com o seu projeto.</p><a href={whatsapp} target="_blank" rel="noopener noreferrer">Quero um pergolado</a></div></article><article><img src={base+photos[2][0]} alt="Cobertura residencial sustentada por estrutura metálica fabricada pela LC" loading="lazy" width="1280" height="960"/><div><span className="service-number">02</span><h3>Estruturas e coberturas</h3><p>Metal para proteger e ampliar as possibilidades do seu imóvel. Da fabricação à montagem no local.</p><a href={whatsapp} target="_blank" rel="noopener noreferrer">Conversar sobre meu projeto</a></div></article></div></section>
 <section className="portfolio section" id="trabalhos"><div className="container"><div className="section-heading"><div><p className="eyebrow">02 / NOSSOS TRABALHOS</p><h2>O resultado fala<br/>pelo trabalho.</h2></div><p>Conheça projetos executados pela LC.<br/>Toque nas fotos para ver os detalhes.</p></div><div className="gallery">{photos.map((p,i)=><figure key={p[0]} className={'project project-'+i}><button className="photo-button" onClick={e=>open(i,e)} aria-label={'Ampliar foto: '+p[1]}><img src={base+p[0]} alt={p[1]+' realizado pela Serralheria LC'} loading="lazy" width="960" height="1280"/><span className="expand">Ampliar +</span></button><figcaption><span className="project-index">0{i+1}</span><div><h3>{p[1]}</h3><p>{p[2]}</p></div></figcaption></figure>)}</div><div className="video-block"><div><p className="eyebrow">DO ANTES AO DEPOIS</p><h3>Veja o espaço<br/>ganhar uma nova forma.</h3><p>Acompanhe a transformação de um projeto no vídeo da Serralheria LC.</p><a className="text-link" href="https://www.instagram.com/serralherialc07/" target="_blank" rel="noopener noreferrer">Mais trabalhos no Instagram</a></div><video controls playsInline preload="none" poster="/images/pergolados/antes-e-depois-pergolado-poster.webp" aria-label="Vídeo antes e depois da instalação de pergolado"><source src="/videos/antes-e-depois-pergolado-serralheria-lc.mp4" type="video/mp4"/>Seu navegador não reproduz este vídeo. <a href="/videos/antes-e-depois-pergolado-serralheria-lc.mp4">Abrir vídeo</a></video></div></div></section>
 <section className="section container about" id="sobre"><div className="about-photo"><img src="/images/fabricacao/fabricacao-artesanal-estrutura-metalica-campo-bom.webp" alt="Profissional da Serralheria LC trabalhando manualmente na fabricação de uma estrutura metálica" width="1280" height="960" loading="lazy"/><span>QUEM FAZ, CUIDA DE CADA DETALHE.</span></div><div><p className="eyebrow">03 / POR QUE ESCOLHER A LC</p><h2>Experiência nas mãos.<br/>Cuidado no resultado.</h2><p className="about-intro">Há mais de 8 anos, colocamos experiência prática em projetos de serralheria. Em Campo Bom e região, o atendimento é direto com quem entende do trabalho.</p><div className="reasons"><article><h3>Feito para o seu espaço</h3><p>Projetos sob medida para necessidades residenciais e comerciais.</p></article><article><h3>Fabricação própria</h3><p>Acompanhamento da produção à instalação, com atenção aos detalhes.</p></article><article><h3>Atendimento próximo</h3><p>Uma conversa clara para entender o que você precisa e avaliar seu projeto.</p></article></div></div></section>
 <section className="process section"><div className="container"><p className="eyebrow">04 / DO PRIMEIRO CONTATO À INSTALAÇÃO</p><h2>Seu projeto começa<br/>com uma conversa.</h2><ol><li><span>01</span><h3>Conte sua ideia</h3><p>Chame no WhatsApp. Envie fotos do espaço e o que você tem em mente.</p></li><li><span>02</span><h3>Avaliamos juntos</h3><p>Entendemos a necessidade, as medidas e os detalhes para preparar o orçamento.</p></li><li><span>03</span><h3>Fabricamos sob medida</h3><p>Com o projeto combinado, começa a produção da sua estrutura.</p></li><li><span>04</span><h3>Instalamos no local</h3><p>Concluímos a montagem para o seu espaço ganhar uma nova possibilidade.</p></li></ol></div></section>
 <section className="cta-section container"><p className="eyebrow">VAMOS TIRAR SEU PROJETO DO PAPEL?</p><h2>Tem um espaço.<br/><em>Tem uma possibilidade.</em></h2><p>Envie uma foto e conte sua ideia. Vamos conversar sobre a melhor solução para o seu projeto.</p><WA>Solicitar meu orçamento</WA><span>Atendimento em Campo Bom e região</span></section>
 <section className="contact section" id="contato"><div className="container contact-grid"><div><p className="eyebrow">05 / FALE COM A LC</p><h2>Perto de você.<br/>Pronto para conversar.</h2></div><div><h3>WhatsApp</h3><a className="phone" href={whatsapp} target="_blank" rel="noopener noreferrer">(51) 99813-3404</a><h3>Onde estamos</h3><address>R. Pres. Castelo Branco, 1730 · Celeste<br/>Campo Bom – RS · CEP 93700-000</address><div className="contact-links"><a href="https://www.google.com/maps/search/?api=1&query=R.%20Pres.%20Castelo%20Branco%201730%20Campo%20Bom%20RS" target="_blank" rel="noopener noreferrer">Como chegar</a><a href="https://www.instagram.com/serralherialc07/" target="_blank" rel="noopener noreferrer">Instagram · @serralherialc07</a></div></div></div></section></main>
 <footer className="container"><a className="brand" href="#"><img src="/images/brand/logo-serralheria-lc.webp" width="56" height="56" alt="Logo Serralheria LC"/><span>SERRALHERIA <b>LC</b><small>CAMPO BOM · RS</small></span></a><p>© {new Date().getFullYear()} Serralheria LC.<br/>Todos os direitos reservados.</p></footer><a className="floating-wa" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Solicitar orçamento pelo WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" strokeWidth="1.7" d="M20.5 11.8a8.5 8.5 0 0 1-12.7 7.4L3 20.5l1.3-4.7A8.5 8.5 0 1 1 20.5 11.8Z"/><path fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" d="m8.5 7.5 1.2 2-1 1c1 2 2 3 4 4l1-1 2 1.2c0 3-7 1.5-8.5-4.5-.3-1.4.1-2.2 1.3-2.7Z"/></svg><span>Orçamento</span></a>
 <dialog ref={dialog} className="lightbox" aria-label="Fotografia ampliada do trabalho" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===dialog.current)close()}}><button className="close-dialog" onClick={close} aria-label="Fechar fotografia">Fechar ×</button>{selected!==null&&<><img src={base+photos[selected][0]} alt={photos[selected][1]}/><p>{photos[selected][1]}</p><div className="dialog-navigation"><button onClick={()=>setSelected((selected+photos.length-1)%photos.length)}>Anterior</button><span>{selected+1} / {photos.length}</span><button onClick={()=>setSelected((selected+1)%photos.length)}>Próxima</button></div></>}</dialog></>}
